### ISSUE TITLE
Erro na versão .NET Framework 4.5.1

### ISSUE THREAD

**Issue by alexandrei2007** [pagarme/TLS-update#13]
Boa tarde, rodando na versão 4.5.1 ocorre o erro:

> Got error! The underlying connection was closed: An unexpected error occurred on a send.

Sendo necessário forçar o TLS:

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by murilohns** [comment]
@alexandrei2007 , obrigado por notificar sobre isso!.

Está sendo implementado o uso do TLS12 na SDK de .Net, você pode acompanhar nesse PR se quiser:
https://github.com/pagarme/pagarme-net/pull/89
